'use client';

import { z } from 'zod';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { useForm, useWatch } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Building2, MapPin, Loader2, Badge } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage
} from '@/components/ui/form';
import { SaveSchema } from '@/schemas/onboarding';
import { skipOnboarding, saveOnboarding } from '@/actions/onboarding';
import { OnboardingFormProps } from '@/types/onboarding';

export function OnboardingForm({ data, isAutoNamed }: OnboardingFormProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [isAutoGeneratedWorkspace, setIsAutoGeneratedWorkspace] = useState(true);
  const [isAutoGeneratedCompany, setIsAutoGeneratedCompany] = useState(isAutoNamed);

  const form = useForm<z.infer<typeof SaveSchema>>({
    resolver: zodResolver(SaveSchema),
    defaultValues: {
      workspaceId: data.workspaceId,
      returnTo: data.returnTo,
      companyName: data.companyName,
      workspaceName: data.workspaceName,
      preferredRegion: data.preferredRegion
    }
  });

  async function onSubmit(data: z.infer<typeof SaveSchema>) {
    startTransition(async () => {
      setError(null);

      const result = await saveOnboarding(data);

      if (result.success) {
        // Check if there's a returnTo URL
        router.push(result.redirectTo || '/');
      } else {
        setError(result.message || 'Setup failed. Please try again.');
      }
    });
  }

  async function handleSkip() {
    startTransition(async () => {
      setError(null);
      const result = await skipOnboarding({
        workspaceId: data.workspaceId,
        returnTo: data.returnTo
      });

      if (result.success) {
        router.push(result.redirectTo || '/');
      }

      toast.error('Skip failed. Please try again.');
    });
  }

  const workspaceName = useWatch({ control: form.control, name: 'workspaceName' });

  return (
    <Card className="border-border shadow-lg">
      <CardHeader className="space-y-1 pb-6">
        <div className="flex items-center justify-between mb-2">
          <div className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
            Setup
          </div>
          <button
            type="button"
            onClick={handleSkip}
            disabled={isPending}
            className="text-sm text-brand-500 hover:text-brand-600 transition-colors cursor-pointer"
          >
            Skip for now
          </button>
        </div>
        <CardTitle className="text-2xl font-semibold text-foreground">
          Set up your workspace
        </CardTitle>
        <CardDescription className="text-muted-foreground">
          This only takes a minute. You can change these anytime.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="space-y-5"
          >
            {error && (
              <div className="p-3 text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded-md">
                {error}
              </div>
            )}

            <FormField
              control={form.control}
              name="companyName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-2">
                    Company / Organisation name (optional)
                    {isAutoGeneratedCompany && data.companyName && (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-muted text-xs text-muted-foreground">
                        <Badge className="w-3 h-3" />
                        Auto-generated
                      </span>
                    )}
                  </FormLabel>
                  <div className="relative">
                    <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <FormControl>
                      <Input
                        placeholder="Acme Inc."
                        className="pl-10"
                        {...field}
                        onChange={(e) => {
                          field.onChange(e);
                          setIsAutoGeneratedCompany(false);
                        }}
                      />
                    </FormControl>
                  </div>
                  <FormDescription>Used for billing and invoices later.</FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="workspaceName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-2">
                    Workspace name
                    {isAutoGeneratedWorkspace && workspaceName && (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-muted text-xs text-muted-foreground">
                        <Badge className="w-3 h-3" />
                        Auto-generated
                      </span>
                    )}
                  </FormLabel>
                  <div className="relative">
                    <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <FormControl>
                      <Input
                        placeholder="My workspace"
                        className="pl-10"
                        {...field}
                        onChange={(e) => {
                          field.onChange(e);
                          setIsAutoGeneratedWorkspace(false);
                        }}
                      />
                    </FormControl>
                  </div>
                  <FormDescription>Shown in the dashboard and invites.</FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="preferredRegion"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Preferred data region</FormLabel>
                  <div className="relative">
                    <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground z-10 pointer-events-none" />
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger className="pl-10">
                          <SelectValue placeholder="Select a region" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="APAC">Asia Pacific</SelectItem>
                        <SelectItem value="AU">Australia</SelectItem>
                        <SelectItem value="EU">Europe</SelectItem>
                        <SelectItem value="UK">United Kingdom</SelectItem>
                        <SelectItem value="US">United States</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="flex gap-3 pt-4">
              <Button
                type="submit"
                className="flex-1 bg-brand-500 hover:bg-brand-600 text-white"
                disabled={isPending}
              >
                {isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Setting up...
                  </>
                ) : (
                  'Continue'
                )}
              </Button>
            </div>

            <div className="text-center pt-2">
              <button
                type="button"
                onClick={handleSkip}
                disabled={isPending}
                className="text-sm text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
              >
                {`I'm just evaluating`}
              </button>
            </div>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
